2024-11-13 06:18:44,014 - app - ERROR - Exception on /forgotPassword/password/Impvc2VtYXJpYTEuam1tcEBnbWFpbC5jb20i.ZzQ2rQ.-V5Ed86xA25I4z1tD1htT2OlTFc [GET]
Traceback (most recent call last):
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/core/decorators/decorators.py", line 14, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/app/modules/forgotPassword/routes.py", line 51, in resetPassword
    return render_template("resetPassword/forgotPasswordConfirmation.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/app/modules/forgotPassword/templates/resetPassword/forgotPasswordConfirmation.html", line 1, in top-level template code
    {% extends "base_template.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/app/templates/base_template.html", line 304, in top-level template code
    {% block scripts %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/app/modules/forgotPassword/templates/resetPassword/forgotPasswordConfirmation.html", line 48, in block 'scripts'
    <script src="{{ url_for('reset.scripts', subfolder='js', filename='scripts.js') }}"></script>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset.scripts' with values ['filename', 'subfolder']. Did you mean 'dataset.scripts' instead?
2024-11-13 06:18:44,019 - app - ERROR - Internal Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2024-11-13 06:23:17,618 - app - ERROR - Exception on /forgotPassword/password/Impvc2VtYXJpYTEuam1tcEBnbWFpbC5jb20i.ZzQ3uw.k-bqM3ynMV3MdLXRUO_5_6_zSPI [GET]
Traceback (most recent call last):
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/core/decorators/decorators.py", line 14, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/app/modules/forgotPassword/routes.py", line 51, in resetPassword
    return render_template("resetPassword/forgotPasswordConfirmation.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/app/modules/forgotPassword/templates/resetPassword/forgotPasswordConfirmation.html", line 1, in top-level template code
    {% extends "base_template.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/app/templates/base_template.html", line 304, in top-level template code
    {% block scripts %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/app/modules/forgotPassword/templates/resetPassword/forgotPasswordConfirmation.html", line 48, in block 'scripts'
    <script src="{{ url_for('reset.assets', subfolder='js', filename='scripts.js') }}"></script>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset.assets' with values ['filename', 'subfolder']. Did you mean 'dataset.datasets' instead?
2024-11-13 06:23:17,621 - app - ERROR - Internal Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
